# Generated by Django 5.1.6 on 2025-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(max_length=50),
        ),
    ]
