# Generated by Django 5.1.6 on 2025-03-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_chatmessage_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")], max_length=20
            ),
        ),
    ]
